version: '3.8'

services:
  web:
    build: .
    container_name: web
    volumes:
      - ./src:/var/www/html
    ports:
      - "6001:80"
    networks:
      - app-network
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "6002:80"
    environment:
      PMA_HOST: db
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.1.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    ports:
      - "6003:3306"
    environment:
      - MYSQL_DATABASE=sendy
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - ./dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

networks:
  sendy:

volumes:
  dbdata:
  src:
